server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Handle React Router — semua route ke index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}