services:

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ilham
      POSTGRES_PASSWORD: ilham123
      POSTGRES_DB: ilham
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ilham"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      DATABASE_URL: postgres://ilham:ilham123@db:5432/ilham?sslmode=disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: a7664cfe0a809b2be798fe9da89e7977e17c9dc03e15f7ddd1446de29e7a899c
      BACKEND_URL: http://shortlink:8080
      FRONTEND_URL: http://shortlink:5173
    depends_on:
      db:
        condition: service_healthy  
      redis:
        condition: service_started
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/.env:/app/.env
    
  migration:
    image: migrate/migrate
    volumes:
      - ./backend/db/migrations:/migrations 
    command:
      - -path=/migrations
      - -database=postgres://ilham:ilham123@db:5432/ilham?sslmode=disable
      - up
    depends_on:
      db:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: http://shortlink:8080
    ports:
      - "5173:80"
    depends_on:
      - backend

  proxy:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  db-data:
